
# ===== Listeners =====
listener 1883 0.0.0.0
protocol mqtt

listener 9001 0.0.0.0
protocol websockets

# ===== Seguridad (solo LAN) =====
allow_anonymous true
password_file /mosquitto/config/passwd # (no usado por allow_anonymous=true)

# ===== Logs =====
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information

# ===== Opcional: ajustar tamaños =====
max_inflight_messages 100
max_queued_messages 1000
message_size_limit 0
